[build]
    command = "npm run build"
    publish = "coschedule-challenge-front-end/build"
    base = "coschedule-challenge-front-end"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200